# Workspace for Project Euler's Problems

[workspace]

members = [
    "utils", "e001", "e002", "e003", "e004", "e005", "e006", "e007", "e008", "e009",
    "e010", "e011", "e012", "e013", "e014", "e015", "e016", "e017",
]
