//! Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
//!     2^2=4,     2^3=8,      2^4=16,     2^5=32
//!     3^2=9,     3^3=27,     3^4=81,     3^5=243
//!     4^2=16,    4^3=64,     4^4=256,    4^5=1024
//!     5^2=25,    5^3=125,    5^4=625,    5^5=3125
//! If they are then placed in numerical order, with any repeats removed,
//! we get the following sequence of 15 distinct terms:
//!     4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
//! How many distinct terms are in the sequence generated by
//! a^b for 2 <= a <= 100 and 2 <= b <= 100?

use std::collections::HashSet;
use utils::big::U1024;

fn answer(target: u32) -> usize {
    let mut distinct_terms: HashSet<U1024> = HashSet::new();

    for base in 2..=(target as u64) {
        let big_base = U1024::from_small(base);
        let mut power = U1024::from_small(base);
        for _exp in 2..=target {
            power *= big_base;
            distinct_terms.insert(power);
        }
    }

    println!("How many distinct terms are in the sequence generated by");
    println!("a^b for 2 <= a <= {0} and 2 <= b <= {0} ?", &target);

    distinct_terms.len()
}

fn main() {
    let a = answer(100);
    println!("\nAnswer: {}\n", &a);
}

////////////////////////////////////////////////////////////

#[cfg(test)]
mod e029_tests {
    use super::*;

    #[test]
    fn check_example() {
        let expected = 15;
        assert_eq!(expected, answer(5));
    }

    #[test]
    fn check_answer() {
        let expected = 9_183;
        assert_eq!(expected, answer(100));
    }
}
